export const config = {
    serverSettings: {
        port: process.env.PORT || 80,
        secure: false,
        keyPath: process.env.SSL_KEY_PATH || null,
        certPath: process.env.SSL_CERT_PATH || null,
        domain: 'localhost',
        baseUrl: process.env.BASE_URL || 'http://localhost:80'
    },
    proxySettings: {
        scrape: true,
        timeout: 2000,
        protocol: "http",
        enableProxy: true,
    },
    facebookBotSettings: {
        skin: {
            names: [
                'fly',
                'spider',
                'lizard',
                'bat',
                'snake',
                'fox',
                'coyote',
                'hunter',
                'sumo',
                'bear',
                'cougar',
                'panther',
                'lion',
                'crocodile',
                'shark',
                'mammoth',
                'raptor',
                't_rex',
                'kraken',
                'tiny_fairy',
                'small_goblin',
                'young_elf',
                'grove_spirit',
                'mystical_dwarf',
                'brave_halfling',
                'wild_werewolf',
                'powerful_sorcerer',
                'stealthy_assassin',
                'valiant_knight',
            ],
            enable: true,
        },
        useMassBoost: false,
    },
};
